# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.


**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. 
- The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

- Your first mission is to familiarize yourself with the **Books to Scrape** website. 
- Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

**Next**, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

- After reviewing the site, you can construct a plan for scraping relevant data. 
- Pay attention to the details displayed for each book, including the title, price, rating, and availability. 
- This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

- In the fast-changing online world, websites often update and change their structures. 
    - When you try this lab, the **Books to Scrape** website might differ from what you expect.

- If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

- You can choose another website that interests you and is suitable for scraping data. 
- Options like Wikipedia, The New York Times, or even library databases are great alternatives. 
- The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. 
- This is your opportunity to practice and adapt to different web environments!

---
# Solved Lab | Web Scraping
---

In [2]:
import requests
url = "https://books.toscrape.com/index.html"
response = requests.get(url)
response

In [4]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

In [5]:
soup.find_all('p', attrs={'class': 'star-rating'})

[<p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>,
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>]

In [28]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm
import time
import re

# Function to extract book details from individual book page
def extract_book_details(book_url):
    details = {
        "UPC": None,
        "Description": None,
        "Genre": None,
        "Availability (Amount)": None,
        "Number of Reviews": None
    }
    
    try:
        response = requests.get(book_url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")
        
        # UPC - look for table row with UPC
        table_rows = soup.find_all("tr")
        for tr in table_rows:
            th = tr.find("th")
            td = tr.find("td")
            if th and td:
                th_text = th.get_text(strip=True)
                if th_text == "UPC":
                    details["UPC"] = td.get_text(strip=True)
                elif th_text == "Number of reviews":
                    details["Number of Reviews"] = td.get_text(strip=True)
        
        # Availability amount - extract number from "In stock (20 available)"
        avail_elem = soup.find("p", class_="instock availability")
        if avail_elem:
            avail_text = avail_elem.get_text(strip=True)
            amount_match = re.search(r'\((\d+) available\)', avail_text)
            if amount_match:
                details["Availability (Amount)"] = amount_match.group(1)
        
        # Description - get first <p> after #product_description
        desc_div = soup.find("div", id="product_description")
        if desc_div:
            desc_p = desc_div.find_next_sibling("p")
            if desc_p:
                details["Description"] = desc_p.get_text(strip=True)
        
        # Genre - third breadcrumb link (index 2)
        breadcrumb_links = soup.select("ul.breadcrumb li a")
        if len(breadcrumb_links) >= 3:
            details["Genre"] = breadcrumb_links[2].get_text(strip=True)
    
    except requests.RequestException as e:
        print(f"Failed to fetch {book_url}: {e}")
    
    # Sleep a bit to be polite
    time.sleep(0.5)
    
    return details

# Load the CSV
books_df = pd.read_csv("books.csv")

all_details = []

# Loop through every book with progress bar
for idx, row in tqdm(books_df.iterrows(), total=len(books_df), desc="Scraping books"):
    book_url = row['Link']
    
    # Convert relative URL to absolute if necessary
    if book_url.startswith("catalogue/"):
        book_url = "https://books.toscrape.com/" + book_url
    
    details = extract_book_details(book_url)
    all_details.append(details)

# Combine original CSV with new details
details_df = pd.DataFrame(all_details)
final_df = pd.concat([books_df, details_df], axis=1)

# Save the full dataset
final_df.to_csv("books_complete_data.csv", index=False)
print("Saved all book details to books_detailed.csv")

Scraping books:   1%|▏         | 1/75 [00:01<01:30,  1.23s/it]

Failed to fetch https://books.toscrape.com/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html

Scraping books:   3%|▎         | 2/75 [00:02<01:17,  1.07s/it]

Failed to fetch https://books.toscrape.com/sophies-world_966/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/sophies-world_966/index.html

Scraping books:   4%|▍         | 3/75 [00:03<01:12,  1.01s/it]

Failed to fetch https://books.toscrape.com/untitled-collection-sabbath-poems-2014_953/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/untitled-collection-sabbath-poems-2014_953/index.html

Scraping books:   5%|▌         | 4/75 [00:04<01:09,  1.02it/s]

Failed to fetch https://books.toscrape.com/this-one-summer_947/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/this-one-summer_947/index.html

Scraping books:   7%|▋         | 5/75 [00:04<01:07,  1.04it/s]

Failed to fetch https://books.toscrape.com/thirst_946/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/thirst_946/index.html

Scraping books:   8%|▊         | 6/75 [00:05<01:06,  1.04it/s]

Failed to fetch https://books.toscrape.com/princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html

Scraping books:   9%|▉         | 7/75 [00:06<01:05,  1.04it/s]

Failed to fetch https://books.toscrape.com/princess-between-worlds-wide-awake-princess-5_919/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/princess-between-worlds-wide-awake-princess-5_919/index.html

Scraping books:  11%|█         | 8/75 [00:07<01:03,  1.05it/s]

Failed to fetch https://books.toscrape.com/outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html

Scraping books:  12%|█▏        | 9/75 [00:08<01:06,  1.00s/it]

Failed to fetch https://books.toscrape.com/mama-tried-traditional-italian-cooking-for-the-screwed-crude-vegan-and-tattooed_908/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/mama-tried-traditional-italian-cooking-for-the-screwed-crude-vegan-and-tattooed_908/index.html

Scraping books:  13%|█▎        | 10/75 [00:10<01:07,  1.04s/it]

Failed to fetch https://books.toscrape.com/first-and-first-five-boroughs-3_893/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/first-and-first-five-boroughs-3_893/index.html

Scraping books:  15%|█▍        | 11/75 [00:11<01:06,  1.04s/it]

Failed to fetch https://books.toscrape.com/camp-midnight_886/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/camp-midnight_886/index.html

Scraping books:  16%|█▌        | 12/75 [00:12<01:04,  1.02s/it]

Failed to fetch https://books.toscrape.com/the-third-wave-an-entrepreneurs-vision-of-the-future_862/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-third-wave-an-entrepreneurs-vision-of-the-future_862/index.html

Scraping books:  17%|█▋        | 13/75 [00:13<01:01,  1.01it/s]

Failed to fetch https://books.toscrape.com/the-stranger_861/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-stranger_861/index.html

Scraping books:  19%|█▊        | 14/75 [00:13<00:59,  1.03it/s]

Failed to fetch https://books.toscrape.com/something-more-than-this_834/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/something-more-than-this_834/index.html

Scraping books:  20%|██        | 15/75 [00:14<00:58,  1.03it/s]

Failed to fetch https://books.toscrape.com/poems-that-make-grown-women-cry_824/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/poems-that-make-grown-women-cry_824/index.html

Scraping books:  21%|██▏       | 16/75 [00:15<00:57,  1.03it/s]

Failed to fetch https://books.toscrape.com/dark-notes_800/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/dark-notes_800/index.html

Scraping books:  23%|██▎       | 17/75 [00:16<00:55,  1.04it/s]

Failed to fetch https://books.toscrape.com/batman-the-dark-knight-returns-batman_792/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/batman-the-dark-knight-returns-batman_792/index.html

Scraping books:  24%|██▍       | 18/75 [00:17<00:54,  1.04it/s]

Failed to fetch https://books.toscrape.com/agnostic-a-spirited-manifesto_786/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/agnostic-a-spirited-manifesto_786/index.html

Scraping books:  25%|██▌       | 19/75 [00:18<00:54,  1.02it/s]

Failed to fetch https://books.toscrape.com/walt-disneys-alice-in-wonderland_777/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/walt-disneys-alice-in-wonderland_777/index.html

Scraping books:  27%|██▋       | 20/75 [00:19<00:54,  1.02it/s]

Failed to fetch https://books.toscrape.com/superman-vol-1-before-truth-superman-by-gene-luen-yang-1_739/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/superman-vol-1-before-truth-superman-by-gene-luen-yang-1_739/index.html

Scraping books:  28%|██▊       | 21/75 [00:20<00:53,  1.01it/s]

Failed to fetch https://books.toscrape.com/old-school-diary-of-a-wimpy-kid-10_723/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/old-school-diary-of-a-wimpy-kid-10_723/index.html

Scraping books:  29%|██▉       | 22/75 [00:21<00:53,  1.01s/it]

Failed to fetch https://books.toscrape.com/lady-midnight-the-dark-artifices-1_707/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/lady-midnight-the-dark-artifices-1_707/index.html

Scraping books:  31%|███       | 23/75 [00:22<00:52,  1.02s/it]

Failed to fetch https://books.toscrape.com/i-am-pilgrim-pilgrim-1_703/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/i-am-pilgrim-pilgrim-1_703/index.html

Scraping books:  32%|███▏      | 24/75 [00:23<00:51,  1.01s/it]

Failed to fetch https://books.toscrape.com/hyperbole-and-a-half-unfortunate-situations-flawed-coping-mechanisms-mayhem-and-other-things-that-happened_702/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/hyperbole-and-a-half-unfortunate-situations-flawed-coping-mechanisms-mayhem-and-other-things-that-happened_702/index.html

Scraping books:  33%|███▎      | 25/75 [00:24<00:49,  1.01it/s]

Failed to fetch https://books.toscrape.com/greek-mythic-history_698/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/greek-mythic-history_698/index.html

Scraping books:  35%|███▍      | 26/75 [00:25<00:48,  1.02it/s]

Failed to fetch https://books.toscrape.com/far-away-places-on-the-brink-of-change-seven-continents-twenty-five-years_694/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/far-away-places-on-the-brink-of-change-seven-continents-twenty-five-years_694/index.html

Scraping books:  36%|███▌      | 27/75 [00:26<00:46,  1.02it/s]

Failed to fetch https://books.toscrape.com/eight-hundred-grapes_690/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/eight-hundred-grapes_690/index.html

Scraping books:  37%|███▋      | 28/75 [00:27<00:45,  1.03it/s]

Failed to fetch https://books.toscrape.com/dear-mr-knightley_684/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/dear-mr-knightley_684/index.html

Scraping books:  39%|███▊      | 29/75 [00:28<00:44,  1.04it/s]

Failed to fetch https://books.toscrape.com/city-of-fallen-angels-the-mortal-instruments-4_677/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/city-of-fallen-angels-the-mortal-instruments-4_677/index.html

Scraping books:  40%|████      | 30/75 [00:29<00:43,  1.04it/s]

Failed to fetch https://books.toscrape.com/the-epidemic-the-program-06_636/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-epidemic-the-program-06_636/index.html

Scraping books:  41%|████▏     | 31/75 [00:30<00:42,  1.03it/s]

Failed to fetch https://books.toscrape.com/one-with-you-crossfire-5_626/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/one-with-you-crossfire-5_626/index.html

Scraping books:  43%|████▎     | 32/75 [00:31<00:41,  1.04it/s]

Failed to fetch https://books.toscrape.com/the-sleep-revolution-transforming-your-life-one-night-at-a-time_608/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-sleep-revolution-transforming-your-life-one-night-at-a-time_608/index.html

Scraping books:  44%|████▍     | 33/75 [00:32<00:40,  1.04it/s]

Failed to fetch https://books.toscrape.com/mother-can-you-not_599/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/mother-can-you-not_599/index.html

Scraping books:  45%|████▌     | 34/75 [00:33<00:39,  1.04it/s]

Failed to fetch https://books.toscrape.com/a-gentlemans-position-society-of-gentlemen-3_584/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-gentlemans-position-society-of-gentlemen-3_584/index.html

Scraping books:  47%|████▋     | 35/75 [00:34<00:38,  1.04it/s]

Failed to fetch https://books.toscrape.com/the-moosewood-cookbook-recipes-from-moosewood-restaurant-ithaca-new-york_574/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-moosewood-cookbook-recipes-from-moosewood-restaurant-ithaca-new-york_574/index.html

Scraping books:  48%|████▊     | 36/75 [00:35<00:37,  1.04it/s]

Failed to fetch https://books.toscrape.com/nano-what-now-finding-your-editing-process-revising-your-nanowrimo-book-and-building-a-writing-career-through-publishing-and-beyond_566/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/nano-what-now-finding-your-editing-process-revising-your-nanowrimo-book-and-building-a-writing-career-through-publishing-and-beyond_566/index.html

Scraping books:  49%|████▉     | 37/75 [00:36<00:36,  1.05it/s]

Failed to fetch https://books.toscrape.com/roller-girl_540/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/roller-girl_540/index.html

Scraping books:  51%|█████     | 38/75 [00:37<00:34,  1.06it/s]

Failed to fetch https://books.toscrape.com/history-of-beauty_521/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/history-of-beauty_521/index.html

Scraping books:  52%|█████▏    | 39/75 [00:38<00:34,  1.06it/s]

Failed to fetch https://books.toscrape.com/the-origin-of-species_499/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-origin-of-species_499/index.html

Scraping books:  53%|█████▎    | 40/75 [00:39<00:34,  1.02it/s]

Failed to fetch https://books.toscrape.com/naturally-lean-125-nourishing-gluten-free-plant-based-recipes-all-under-300-calories_479/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/naturally-lean-125-nourishing-gluten-free-plant-based-recipes-all-under-300-calories_479/index.html

Scraping books:  55%|█████▍    | 41/75 [00:40<00:33,  1.01it/s]

Failed to fetch https://books.toscrape.com/life-of-pi_475/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/life-of-pi_475/index.html

Scraping books:  56%|█████▌    | 42/75 [00:41<00:32,  1.03it/s]

Failed to fetch https://books.toscrape.com/every-heart-a-doorway-every-heart-a-doorway-1_465/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/every-heart-a-doorway-every-heart-a-doorway-1_465/index.html

Scraping books:  57%|█████▋    | 43/75 [00:42<00:30,  1.04it/s]

Failed to fetch https://books.toscrape.com/counted-with-the-stars-out-from-egypt-1_463/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/counted-with-the-stars-out-from-egypt-1_463/index.html

Scraping books:  59%|█████▊    | 44/75 [00:43<00:29,  1.04it/s]

Failed to fetch https://books.toscrape.com/the-hobbit-middle-earth-universe_447/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-hobbit-middle-earth-universe_447/index.html

Scraping books:  60%|██████    | 45/75 [00:44<00:28,  1.05it/s]

Failed to fetch https://books.toscrape.com/the-collected-poems-of-wb-yeats-the-collected-works-of-wb-yeats-1_441/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-collected-poems-of-wb-yeats-the-collected-works-of-wb-yeats-1_441/index.html

Scraping books:  61%|██████▏   | 46/75 [00:44<00:27,  1.05it/s]

Failed to fetch https://books.toscrape.com/pride-and-prejudice_437/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/pride-and-prejudice_437/index.html

Scraping books:  63%|██████▎   | 47/75 [00:45<00:26,  1.05it/s]

Failed to fetch https://books.toscrape.com/the-secret-garden_413/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-secret-garden_413/index.html

Scraping books:  64%|██████▍   | 48/75 [00:46<00:26,  1.03it/s]

Failed to fetch https://books.toscrape.com/the-power-greens-cookbook-140-delicious-superfood-recipes_410/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-power-greens-cookbook-140-delicious-superfood-recipes_410/index.html

Scraping books:  65%|██████▌   | 49/75 [00:47<00:24,  1.05it/s]

Failed to fetch https://books.toscrape.com/the-darkest-corners_399/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-darkest-corners_399/index.html

Scraping books:  67%|██████▋   | 50/75 [00:48<00:23,  1.06it/s]

Failed to fetch https://books.toscrape.com/shiver-the-wolves-of-mercy-falls-1_392/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/shiver-the-wolves-of-mercy-falls-1_392/index.html

Scraping books:  68%|██████▊   | 51/75 [00:49<00:22,  1.06it/s]

Failed to fetch https://books.toscrape.com/kill-the-boy-band_381/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/kill-the-boy-band_381/index.html

Scraping books:  69%|██████▉   | 52/75 [00:50<00:21,  1.06it/s]

Failed to fetch https://books.toscrape.com/booked_365/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/booked_365/index.html

Scraping books:  71%|███████   | 53/75 [00:51<00:20,  1.05it/s]

Failed to fetch https://books.toscrape.com/an-abundance-of-katherines_362/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/an-abundance-of-katherines_362/index.html

Scraping books:  72%|███████▏  | 54/75 [00:52<00:20,  1.05it/s]

Failed to fetch https://books.toscrape.com/a-feast-for-crows-a-song-of-ice-and-fire-4_357/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-feast-for-crows-a-song-of-ice-and-fire-4_357/index.html

Scraping books:  73%|███████▎  | 55/75 [00:53<00:19,  1.04it/s]

Failed to fetch https://books.toscrape.com/the-gunning-of-america-business-and-the-making-of-american-gun-culture_347/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-gunning-of-america-business-and-the-making-of-american-gun-culture_347/index.html

Scraping books:  75%|███████▍  | 56/75 [00:54<00:18,  1.03it/s]

Failed to fetch https://books.toscrape.com/some-women_341/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/some-women_341/index.html

Scraping books:  76%|███████▌  | 57/75 [00:55<00:17,  1.04it/s]

Failed to fetch https://books.toscrape.com/outlander-outlander-1_338/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/outlander-outlander-1_338/index.html

Scraping books:  77%|███████▋  | 58/75 [00:56<00:16,  1.05it/s]

Failed to fetch https://books.toscrape.com/night-shift-night-shift-1-20_335/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/night-shift-night-shift-1-20_335/index.html

Scraping books:  79%|███████▊  | 59/75 [00:57<00:15,  1.05it/s]

Failed to fetch https://books.toscrape.com/the-elegant-universe-superstrings-hidden-dimensions-and-the-quest-for-the-ultimate-theory_245/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-elegant-universe-superstrings-hidden-dimensions-and-the-quest-for-the-ultimate-theory_245/index.html

Scraping books:  80%|████████  | 60/75 [00:58<00:14,  1.06it/s]

Failed to fetch https://books.toscrape.com/scarlet-the-lunar-chronicles-2_218/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/scarlet-the-lunar-chronicles-2_218/index.html

Scraping books:  81%|████████▏ | 61/75 [00:59<00:13,  1.06it/s]

Failed to fetch https://books.toscrape.com/running-with-scissors_215/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/running-with-scissors_215/index.html

Scraping books:  83%|████████▎ | 62/75 [01:00<00:12,  1.07it/s]

Failed to fetch https://books.toscrape.com/ready-player-one_209/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/ready-player-one_209/index.html

Scraping books:  84%|████████▍ | 63/75 [01:01<00:11,  1.05it/s]

Failed to fetch https://books.toscrape.com/green-eggs-and-ham-beginner-books-b-16_165/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/green-eggs-and-ham-beginner-books-b-16_165/index.html

Scraping books:  85%|████████▌ | 64/75 [01:02<00:10,  1.05it/s]

Failed to fetch https://books.toscrape.com/fifty-shades-freed-fifty-shades-3_156/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/fifty-shades-freed-fifty-shades-3_156/index.html

Scraping books:  87%|████████▋ | 65/75 [01:03<00:09,  1.04it/s]

Failed to fetch https://books.toscrape.com/disrupted-my-misadventure-in-the-start-up-bubble_148/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/disrupted-my-misadventure-in-the-start-up-bubble_148/index.html

Scraping books:  88%|████████▊ | 66/75 [01:04<00:08,  1.05it/s]

Failed to fetch https://books.toscrape.com/a-visit-from-the-goon-squad_117/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-visit-from-the-goon-squad_117/index.html

Scraping books:  89%|████████▉ | 67/75 [01:05<00:07,  1.02it/s]

Failed to fetch https://books.toscrape.com/new-moon-twilight-2_105/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/new-moon-twilight-2_105/index.html

Scraping books:  91%|█████████ | 68/75 [01:06<00:06,  1.03it/s]

Failed to fetch https://books.toscrape.com/fruits-basket-vol-2-fruits-basket-2_100/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/fruits-basket-vol-2-fruits-basket-2_100/index.html

Scraping books:  92%|█████████▏| 69/75 [01:06<00:05,  1.05it/s]

Failed to fetch https://books.toscrape.com/y-the-last-man-vol-1-unmanned-y-the-last-man-1_98/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/y-the-last-man-vol-1-unmanned-y-the-last-man-1_98/index.html

Scraping books:  93%|█████████▎| 70/75 [01:07<00:04,  1.05it/s]

Failed to fetch https://books.toscrape.com/the-zombie-room_87/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-zombie-room_87/index.html

Scraping books:  95%|█████████▍| 71/75 [01:08<00:03,  1.01it/s]

Failed to fetch https://books.toscrape.com/the-silent-wife_83/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-silent-wife_83/index.html

Scraping books:  96%|█████████▌| 72/75 [01:09<00:02,  1.01it/s]

Failed to fetch https://books.toscrape.com/the-girl-you-lost_66/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-girl-you-lost_66/index.html

Scraping books:  97%|█████████▋| 73/75 [01:10<00:01,  1.01it/s]

Failed to fetch https://books.toscrape.com/the-edge-of-reason-bridget-jones-2_63/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-edge-of-reason-bridget-jones-2_63/index.html

Scraping books:  99%|█████████▊| 74/75 [01:11<00:00,  1.03it/s]

Failed to fetch https://books.toscrape.com/a-spys-devotion-the-regency-spies-of-london-1_3/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-spys-devotion-the-regency-spies-of-london-1_3/index.html

Scraping books: 100%|██████████| 75/75 [01:12<00:00,  1.03it/s]

Saved all book details to books_detailed.csv

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm  # For a nice progress bar
import time

# Function to extract book details from individual book page
def extract_book_details(book_url):
    details = {
        "UPC": None,
        "Description": None,
        "Genre": None,
        "Availability (Amount)": None,
        "Number of Reviews": None
    }
    
    try:
        response = requests.get(book_url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")
        
        # UPC
        upc_elem = soup.select_one("th:contains('UPC') + td")
        if upc_elem:
            details["UPC"] = upc_elem.text.strip()
        
        # Availability amount
        avail_elem = soup.select_one("th:contains('Availability') + td")
        if avail_elem:
            details["Availability (Amount)"] = avail_elem.text.strip()
        
        # Number of reviews
        reviews_elem = soup.select_one("th:contains('Number of reviews') + td")
        if reviews_elem:
            details["Number of Reviews"] = reviews_elem.text.strip()
        
        # Description
        desc_elem = soup.select_one("#product_description")
        if desc_elem:
            # Description is in the next <p> tag after the h2
            desc_paragraph = desc_elem.find_next_sibling("p")
            if desc_paragraph:
                details["Description"] = desc_paragraph.text.strip()
        
        # Genre
        breadcrumb = soup.select("ul.breadcrumb li a")
        if len(breadcrumb) >= 3:
            details["Genre"] = breadcrumb[2].text.strip()
    
    except requests.RequestException as e:
        print(f"Failed to fetch {book_url}: {e}")
    
    # Sleep a bit to be polite
    time.sleep(0.5)
    
    return details

# Load the CSV
books_df = pd.read_csv("books.csv")

all_details = []

# Loop through every book with progress bar
for idx, row in tqdm(books_df.iterrows(), total=len(books_df), desc="Scraping books"):
    book_url = row['Link']
    
    # Convert relative URL to absolute if necessary
    if book_url.startswith("catalogue/"):
        book_url = "https://books.toscrape.com/" + book_url
    
    details = extract_book_details(book_url)
    all_details.append(details)

# Combine original CSV with new details
details_df = pd.DataFrame(all_details)
final_df = pd.concat([books_df, details_df], axis=1)

# Save the full dataset
final_df.to_csv("books_detailed.csv", index=False)
print("Saved all book details to books_detailed.csv")

Scraping books:   0%|          | 0/75 [00:00<?, ?it/s]c:\Users\sboub\anaconda3\Lib\site-packages\soupsieve\css_parser.py:856: FutureWarning: The pseudo class ':contains' is deprecated, ':-soup-contains' should be used moving forward.
  warnings.warn(  # noqa: B028
Scraping books:   1%|▏         | 1/75 [00:01<01:23,  1.13s/it]

Failed to fetch https://books.toscrape.com/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html

Scraping books:   3%|▎         | 2/75 [00:02<01:16,  1.05s/it]

Failed to fetch https://books.toscrape.com/sophies-world_966/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/sophies-world_966/index.html

Scraping books:   4%|▍         | 3/75 [00:03<01:14,  1.03s/it]

Failed to fetch https://books.toscrape.com/untitled-collection-sabbath-poems-2014_953/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/untitled-collection-sabbath-poems-2014_953/index.html

Scraping books:   5%|▌         | 4/75 [00:04<01:14,  1.05s/it]

Failed to fetch https://books.toscrape.com/this-one-summer_947/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/this-one-summer_947/index.html

Scraping books:   7%|▋         | 5/75 [00:05<01:13,  1.05s/it]

Failed to fetch https://books.toscrape.com/thirst_946/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/thirst_946/index.html

Scraping books:   8%|▊         | 6/75 [00:06<01:11,  1.03s/it]

Failed to fetch https://books.toscrape.com/princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html

Scraping books:   9%|▉         | 7/75 [00:07<01:09,  1.02s/it]

Failed to fetch https://books.toscrape.com/princess-between-worlds-wide-awake-princess-5_919/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/princess-between-worlds-wide-awake-princess-5_919/index.html

Scraping books:  11%|█         | 8/75 [00:08<01:09,  1.03s/it]

Failed to fetch https://books.toscrape.com/outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html

Scraping books:  12%|█▏        | 9/75 [00:09<01:10,  1.06s/it]

Failed to fetch https://books.toscrape.com/mama-tried-traditional-italian-cooking-for-the-screwed-crude-vegan-and-tattooed_908/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/mama-tried-traditional-italian-cooking-for-the-screwed-crude-vegan-and-tattooed_908/index.html

Scraping books:  13%|█▎        | 10/75 [00:10<01:06,  1.03s/it]

Failed to fetch https://books.toscrape.com/first-and-first-five-boroughs-3_893/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/first-and-first-five-boroughs-3_893/index.html

Scraping books:  15%|█▍        | 11/75 [00:11<01:03,  1.01it/s]

Failed to fetch https://books.toscrape.com/camp-midnight_886/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/camp-midnight_886/index.html

Scraping books:  16%|█▌        | 12/75 [00:12<01:01,  1.03it/s]

Failed to fetch https://books.toscrape.com/the-third-wave-an-entrepreneurs-vision-of-the-future_862/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-third-wave-an-entrepreneurs-vision-of-the-future_862/index.html

Scraping books:  17%|█▋        | 13/75 [00:13<01:02,  1.01s/it]

Failed to fetch https://books.toscrape.com/the-stranger_861/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-stranger_861/index.html

Scraping books:  19%|█▊        | 14/75 [00:14<01:03,  1.04s/it]

Failed to fetch https://books.toscrape.com/something-more-than-this_834/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/something-more-than-this_834/index.html

Scraping books:  20%|██        | 15/75 [00:15<01:01,  1.03s/it]

Failed to fetch https://books.toscrape.com/poems-that-make-grown-women-cry_824/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/poems-that-make-grown-women-cry_824/index.html

Scraping books:  21%|██▏       | 16/75 [00:16<01:01,  1.05s/it]

Failed to fetch https://books.toscrape.com/dark-notes_800/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/dark-notes_800/index.html

Scraping books:  23%|██▎       | 17/75 [00:17<00:59,  1.03s/it]

Failed to fetch https://books.toscrape.com/batman-the-dark-knight-returns-batman_792/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/batman-the-dark-knight-returns-batman_792/index.html

Scraping books:  24%|██▍       | 18/75 [00:18<00:56,  1.00it/s]

Failed to fetch https://books.toscrape.com/agnostic-a-spirited-manifesto_786/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/agnostic-a-spirited-manifesto_786/index.html

Scraping books:  25%|██▌       | 19/75 [00:19<00:54,  1.02it/s]

Failed to fetch https://books.toscrape.com/walt-disneys-alice-in-wonderland_777/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/walt-disneys-alice-in-wonderland_777/index.html

Scraping books:  27%|██▋       | 20/75 [00:20<00:52,  1.04it/s]

Failed to fetch https://books.toscrape.com/superman-vol-1-before-truth-superman-by-gene-luen-yang-1_739/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/superman-vol-1-before-truth-superman-by-gene-luen-yang-1_739/index.html

Scraping books:  28%|██▊       | 21/75 [00:21<00:50,  1.06it/s]

Failed to fetch https://books.toscrape.com/old-school-diary-of-a-wimpy-kid-10_723/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/old-school-diary-of-a-wimpy-kid-10_723/index.html

Scraping books:  29%|██▉       | 22/75 [00:22<00:49,  1.06it/s]

Failed to fetch https://books.toscrape.com/lady-midnight-the-dark-artifices-1_707/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/lady-midnight-the-dark-artifices-1_707/index.html

Scraping books:  31%|███       | 23/75 [00:23<00:48,  1.07it/s]

Failed to fetch https://books.toscrape.com/i-am-pilgrim-pilgrim-1_703/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/i-am-pilgrim-pilgrim-1_703/index.html

Scraping books:  32%|███▏      | 24/75 [00:23<00:47,  1.08it/s]

Failed to fetch https://books.toscrape.com/hyperbole-and-a-half-unfortunate-situations-flawed-coping-mechanisms-mayhem-and-other-things-that-happened_702/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/hyperbole-and-a-half-unfortunate-situations-flawed-coping-mechanisms-mayhem-and-other-things-that-happened_702/index.html

Scraping books:  33%|███▎      | 25/75 [00:24<00:46,  1.07it/s]

Failed to fetch https://books.toscrape.com/greek-mythic-history_698/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/greek-mythic-history_698/index.html

Scraping books:  35%|███▍      | 26/75 [00:25<00:45,  1.07it/s]

Failed to fetch https://books.toscrape.com/far-away-places-on-the-brink-of-change-seven-continents-twenty-five-years_694/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/far-away-places-on-the-brink-of-change-seven-continents-twenty-five-years_694/index.html

Scraping books:  36%|███▌      | 27/75 [00:26<00:44,  1.07it/s]

Failed to fetch https://books.toscrape.com/eight-hundred-grapes_690/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/eight-hundred-grapes_690/index.html

Scraping books:  37%|███▋      | 28/75 [00:27<00:43,  1.07it/s]

Failed to fetch https://books.toscrape.com/dear-mr-knightley_684/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/dear-mr-knightley_684/index.html

Scraping books:  39%|███▊      | 29/75 [00:28<00:42,  1.07it/s]

Failed to fetch https://books.toscrape.com/city-of-fallen-angels-the-mortal-instruments-4_677/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/city-of-fallen-angels-the-mortal-instruments-4_677/index.html

Scraping books:  40%|████      | 30/75 [00:29<00:41,  1.07it/s]

Failed to fetch https://books.toscrape.com/the-epidemic-the-program-06_636/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-epidemic-the-program-06_636/index.html

Scraping books:  41%|████▏     | 31/75 [00:30<00:41,  1.07it/s]

Failed to fetch https://books.toscrape.com/one-with-you-crossfire-5_626/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/one-with-you-crossfire-5_626/index.html

Scraping books:  43%|████▎     | 32/75 [00:31<00:40,  1.07it/s]

Failed to fetch https://books.toscrape.com/the-sleep-revolution-transforming-your-life-one-night-at-a-time_608/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-sleep-revolution-transforming-your-life-one-night-at-a-time_608/index.html

Scraping books:  44%|████▍     | 33/75 [00:32<00:38,  1.08it/s]

Failed to fetch https://books.toscrape.com/mother-can-you-not_599/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/mother-can-you-not_599/index.html

Scraping books:  45%|████▌     | 34/75 [00:33<00:37,  1.08it/s]

Failed to fetch https://books.toscrape.com/a-gentlemans-position-society-of-gentlemen-3_584/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-gentlemans-position-society-of-gentlemen-3_584/index.html

Scraping books:  47%|████▋     | 35/75 [00:34<00:36,  1.08it/s]

Failed to fetch https://books.toscrape.com/the-moosewood-cookbook-recipes-from-moosewood-restaurant-ithaca-new-york_574/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-moosewood-cookbook-recipes-from-moosewood-restaurant-ithaca-new-york_574/index.html

Scraping books:  48%|████▊     | 36/75 [00:35<00:36,  1.07it/s]

Failed to fetch https://books.toscrape.com/nano-what-now-finding-your-editing-process-revising-your-nanowrimo-book-and-building-a-writing-career-through-publishing-and-beyond_566/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/nano-what-now-finding-your-editing-process-revising-your-nanowrimo-book-and-building-a-writing-career-through-publishing-and-beyond_566/index.html

Scraping books:  49%|████▉     | 37/75 [00:36<00:35,  1.07it/s]

Failed to fetch https://books.toscrape.com/roller-girl_540/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/roller-girl_540/index.html

Scraping books:  51%|█████     | 38/75 [00:37<00:34,  1.08it/s]

Failed to fetch https://books.toscrape.com/history-of-beauty_521/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/history-of-beauty_521/index.html

Scraping books:  52%|█████▏    | 39/75 [00:37<00:33,  1.08it/s]

Failed to fetch https://books.toscrape.com/the-origin-of-species_499/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-origin-of-species_499/index.html

Scraping books:  53%|█████▎    | 40/75 [00:38<00:32,  1.07it/s]

Failed to fetch https://books.toscrape.com/naturally-lean-125-nourishing-gluten-free-plant-based-recipes-all-under-300-calories_479/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/naturally-lean-125-nourishing-gluten-free-plant-based-recipes-all-under-300-calories_479/index.html

Scraping books:  55%|█████▍    | 41/75 [00:39<00:31,  1.08it/s]

Failed to fetch https://books.toscrape.com/life-of-pi_475/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/life-of-pi_475/index.html

Scraping books:  56%|█████▌    | 42/75 [00:40<00:30,  1.09it/s]

Failed to fetch https://books.toscrape.com/every-heart-a-doorway-every-heart-a-doorway-1_465/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/every-heart-a-doorway-every-heart-a-doorway-1_465/index.html

Scraping books:  57%|█████▋    | 43/75 [00:41<00:29,  1.08it/s]

Failed to fetch https://books.toscrape.com/counted-with-the-stars-out-from-egypt-1_463/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/counted-with-the-stars-out-from-egypt-1_463/index.html

Scraping books:  59%|█████▊    | 44/75 [00:42<00:28,  1.09it/s]

Failed to fetch https://books.toscrape.com/the-hobbit-middle-earth-universe_447/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-hobbit-middle-earth-universe_447/index.html

Scraping books:  60%|██████    | 45/75 [00:43<00:27,  1.08it/s]

Failed to fetch https://books.toscrape.com/the-collected-poems-of-wb-yeats-the-collected-works-of-wb-yeats-1_441/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-collected-poems-of-wb-yeats-the-collected-works-of-wb-yeats-1_441/index.html

Scraping books:  61%|██████▏   | 46/75 [00:44<00:26,  1.09it/s]

Failed to fetch https://books.toscrape.com/pride-and-prejudice_437/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/pride-and-prejudice_437/index.html

Scraping books:  63%|██████▎   | 47/75 [00:45<00:25,  1.09it/s]

Failed to fetch https://books.toscrape.com/the-secret-garden_413/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-secret-garden_413/index.html

Scraping books:  64%|██████▍   | 48/75 [00:46<00:24,  1.09it/s]

Failed to fetch https://books.toscrape.com/the-power-greens-cookbook-140-delicious-superfood-recipes_410/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-power-greens-cookbook-140-delicious-superfood-recipes_410/index.html

Scraping books:  65%|██████▌   | 49/75 [00:47<00:23,  1.09it/s]

Failed to fetch https://books.toscrape.com/the-darkest-corners_399/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-darkest-corners_399/index.html

Scraping books:  67%|██████▋   | 50/75 [00:48<00:22,  1.09it/s]

Failed to fetch https://books.toscrape.com/shiver-the-wolves-of-mercy-falls-1_392/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/shiver-the-wolves-of-mercy-falls-1_392/index.html

Scraping books:  68%|██████▊   | 51/75 [00:48<00:21,  1.09it/s]

Failed to fetch https://books.toscrape.com/kill-the-boy-band_381/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/kill-the-boy-band_381/index.html

Scraping books:  69%|██████▉   | 52/75 [00:49<00:21,  1.09it/s]

Failed to fetch https://books.toscrape.com/booked_365/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/booked_365/index.html

Scraping books:  71%|███████   | 53/75 [00:50<00:20,  1.07it/s]

Failed to fetch https://books.toscrape.com/an-abundance-of-katherines_362/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/an-abundance-of-katherines_362/index.html

Scraping books:  72%|███████▏  | 54/75 [00:51<00:19,  1.07it/s]

Failed to fetch https://books.toscrape.com/a-feast-for-crows-a-song-of-ice-and-fire-4_357/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-feast-for-crows-a-song-of-ice-and-fire-4_357/index.html

Scraping books:  73%|███████▎  | 55/75 [00:52<00:18,  1.06it/s]

Failed to fetch https://books.toscrape.com/the-gunning-of-america-business-and-the-making-of-american-gun-culture_347/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-gunning-of-america-business-and-the-making-of-american-gun-culture_347/index.html

Scraping books:  75%|███████▍  | 56/75 [00:53<00:17,  1.07it/s]

Failed to fetch https://books.toscrape.com/some-women_341/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/some-women_341/index.html

Scraping books:  76%|███████▌  | 57/75 [00:54<00:16,  1.08it/s]

Failed to fetch https://books.toscrape.com/outlander-outlander-1_338/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/outlander-outlander-1_338/index.html

Scraping books:  77%|███████▋  | 58/75 [00:55<00:15,  1.08it/s]

Failed to fetch https://books.toscrape.com/night-shift-night-shift-1-20_335/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/night-shift-night-shift-1-20_335/index.html

Scraping books:  79%|███████▊  | 59/75 [00:56<00:14,  1.09it/s]

Failed to fetch https://books.toscrape.com/the-elegant-universe-superstrings-hidden-dimensions-and-the-quest-for-the-ultimate-theory_245/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-elegant-universe-superstrings-hidden-dimensions-and-the-quest-for-the-ultimate-theory_245/index.html

Scraping books:  80%|████████  | 60/75 [00:57<00:13,  1.08it/s]

Failed to fetch https://books.toscrape.com/scarlet-the-lunar-chronicles-2_218/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/scarlet-the-lunar-chronicles-2_218/index.html

Scraping books:  81%|████████▏ | 61/75 [00:58<00:12,  1.08it/s]

Failed to fetch https://books.toscrape.com/running-with-scissors_215/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/running-with-scissors_215/index.html

Scraping books:  83%|████████▎ | 62/75 [00:59<00:12,  1.08it/s]

Failed to fetch https://books.toscrape.com/ready-player-one_209/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/ready-player-one_209/index.html

Scraping books:  84%|████████▍ | 63/75 [01:00<00:11,  1.07it/s]

Failed to fetch https://books.toscrape.com/green-eggs-and-ham-beginner-books-b-16_165/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/green-eggs-and-ham-beginner-books-b-16_165/index.html

Scraping books:  85%|████████▌ | 64/75 [01:01<00:10,  1.07it/s]

Failed to fetch https://books.toscrape.com/fifty-shades-freed-fifty-shades-3_156/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/fifty-shades-freed-fifty-shades-3_156/index.html

Scraping books:  87%|████████▋ | 65/75 [01:02<00:09,  1.07it/s]

Failed to fetch https://books.toscrape.com/disrupted-my-misadventure-in-the-start-up-bubble_148/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/disrupted-my-misadventure-in-the-start-up-bubble_148/index.html

Scraping books:  88%|████████▊ | 66/75 [01:03<00:09,  1.01s/it]

Failed to fetch https://books.toscrape.com/a-visit-from-the-goon-squad_117/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-visit-from-the-goon-squad_117/index.html

Scraping books:  89%|████████▉ | 67/75 [01:04<00:07,  1.02it/s]

Failed to fetch https://books.toscrape.com/new-moon-twilight-2_105/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/new-moon-twilight-2_105/index.html

Scraping books:  91%|█████████ | 68/75 [01:05<00:06,  1.00it/s]

Failed to fetch https://books.toscrape.com/fruits-basket-vol-2-fruits-basket-2_100/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/fruits-basket-vol-2-fruits-basket-2_100/index.html

Scraping books:  92%|█████████▏| 69/75 [01:06<00:05,  1.02it/s]

Failed to fetch https://books.toscrape.com/y-the-last-man-vol-1-unmanned-y-the-last-man-1_98/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/y-the-last-man-vol-1-unmanned-y-the-last-man-1_98/index.html

Scraping books:  93%|█████████▎| 70/75 [01:07<00:04,  1.04it/s]

Failed to fetch https://books.toscrape.com/the-zombie-room_87/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-zombie-room_87/index.html

Scraping books:  95%|█████████▍| 71/75 [01:07<00:03,  1.06it/s]

Failed to fetch https://books.toscrape.com/the-silent-wife_83/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-silent-wife_83/index.html

Scraping books:  96%|█████████▌| 72/75 [01:08<00:02,  1.07it/s]

Failed to fetch https://books.toscrape.com/the-girl-you-lost_66/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-girl-you-lost_66/index.html

Scraping books:  97%|█████████▋| 73/75 [01:09<00:01,  1.07it/s]

Failed to fetch https://books.toscrape.com/the-edge-of-reason-bridget-jones-2_63/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-edge-of-reason-bridget-jones-2_63/index.html

Scraping books:  99%|█████████▊| 74/75 [01:10<00:00,  1.07it/s]

Failed to fetch https://books.toscrape.com/a-spys-devotion-the-regency-spies-of-london-1_3/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-spys-devotion-the-regency-spies-of-london-1_3/index.html

Scraping books: 100%|██████████| 75/75 [01:11<00:00,  1.05it/s]

Saved all book details to books_detailed.csv

In [27]:
final_df.head()

,Title,Price (£),Rating,Availability,Link,UPC,Description,Genre,Availability (Amount),Number of Reviews
0,Set Me Free,17.46,5,In stock,https://books.toscrape.com/catalogue/set-me-fr...,ce6396b0f23f6ecc,Aaron Ledbetterâs future had been planned ou...,Young Adult,In stock (19 available),0
1,The Four Agreements: A Practical Guide to Pers...,17.66,5,In stock,https://books.toscrape.com/the-four-agreements...,None,None,None,None,None
2,Sophie's World,15.94,5,In stock,https://books.toscrape.com/sophies-world_966/i...,None,None,None,None,None
3,Untitled Collection: Sabbath Poems 2014,14.27,4,In stock,https://books.toscrape.com/untitled-collection...,None,None,None,None,None
4,This One Summer,19.49,4,In stock,https://books.toscrape.com/this-one-summer_947...,None,None,None,None,None

In [24]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import re

# Load previously scraped books CSV
books_df = pd.read_csv("books.csv")

def extract_book_details(url):
    """Extract UPC, description, genre, availability, and number of reviews from a book page"""
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")
        
        # Extract product table info
        table_rows = soup.select("table.table.table-striped tr")
        details = {}
        for row in table_rows:
            header = row.select_one("th").text.strip()
            value = row.select_one("td").text.strip()
            if header == "UPC":
                details["UPC"] = value
            elif header == "Availability":
                details["Availability_Details"] = value
            elif header == "Number of reviews":
                details["Number_of_Reviews"] = int(value)
        
        # Extract description
        desc_elem = soup.select_one("#product_description ~ p")
        description = desc_elem.text.strip() if desc_elem else ""
        details["Description"] = description
        
        # Extract genre (breadcrumb)
        breadcrumb = soup.select("ul.breadcrumb li a")
        genre = breadcrumb[2].text.strip() if len(breadcrumb) >= 3 else ""
        details["Genre"] = genre
        
        return details
    except requests.RequestException as e:
        print(f"Failed to fetch {url}: {e}")
        return {"UPC": "", "Availability_Details": "", "Number_of_Reviews": 0, "Description": "", "Genre": ""}

# Loop through each book and extract details
all_details = []
for idx, row in books_df.iterrows():
    print(f"Processing {idx+1}/{len(books_df)}: {row['Title']}")
    book_url = row['Link']
    details = extract_book_details(book_url)
    all_details.append(details)

# Combine with original DataFrame
details_df = pd.DataFrame(all_details)
final_df = pd.concat([books_df, details_df], axis=1)

# Save to CSV
final_df.to_csv("books_detailed.csv", index=False)
print("Saved detailed book data to books_detailed.csv")
print("shape", final_df.shape[0])
final_df.head()

Processing 1/75: Set Me Free
Processing 2/75: The Four Agreements: A Practical Guide to Personal Freedom
Failed to fetch https://books.toscrape.com/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html
Processing 3/75: Sophie's World
Failed to fetch https://books.toscrape.com/sophies-world_966/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/sophies-world_966/index.html
Processing 4/75: Untitled Collection: Sabbath Poems 2014
Failed to fetch https://books.toscrape.com/untitled-collection-sabbath-poems-2014_953/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/untitled-collection-sabbath-poems-2014_953/index.html
Processing 5/75: This One Summer
Failed to fetch https://books.toscrape.com/this-one-summer_947/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/this-one-summer_947/index.html
Processing 6/75: Thirst
Failed to fetch https://books.toscrape.com/thirst_946/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/thirst_946/index.html
Processing 7/75: Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)
Failed to fetch https://books.toscrape.com/princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html
Processing 8/75: Princess Between Worlds (Wide-Awake Princess #5)
Failed to fetch https://books.toscrape.com/princess-between-worlds-wide-awake-princess-5_919/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/princess-between-worlds-wide-awake-princess-5_919/index.html
Processing 9/75: Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)
Failed to fetch https://books.toscrape.com/outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html
Processing 10/75: Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed
Failed to fetch https://books.toscrape.com/mama-tried-traditional-italian-cooking-for-the-screwed-crude-vegan-and-tattooed_908/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/mama-tried-traditional-italian-cooking-for-the-screwed-crude-vegan-and-tattooed_908/index.html
Processing 11/75: First and First (Five Boroughs #3)
Failed to fetch https://books.toscrape.com/first-and-first-five-boroughs-3_893/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/first-and-first-five-boroughs-3_893/index.html
Processing 12/75: Camp Midnight
Failed to fetch https://books.toscrape.com/camp-midnight_886/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/camp-midnight_886/index.html
Processing 13/75: The Third Wave: An Entrepreneurâs Vision of the Future
Failed to fetch https://books.toscrape.com/the-third-wave-an-entrepreneurs-vision-of-the-future_862/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-third-wave-an-entrepreneurs-vision-of-the-future_862/index.html
Processing 14/75: The Stranger
Failed to fetch https://books.toscrape.com/the-stranger_861/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-stranger_861/index.html
Processing 15/75: Something More Than This
Failed to fetch https://books.toscrape.com/something-more-than-this_834/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/something-more-than-this_834/index.html
Processing 16/75: Poems That Make Grown Women Cry
Failed to fetch https://books.toscrape.com/poems-that-make-grown-women-cry_824/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/poems-that-make-grown-women-cry_824/index.html
Processing 17/75: Dark Notes
Failed to fetch https://books.toscrape.com/dark-notes_800/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/dark-notes_800/index.html
Processing 18/75: Batman: The Dark Knight Returns (Batman)
Failed to fetch https://books.toscrape.com/batman-the-dark-knight-returns-batman_792/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/batman-the-dark-knight-returns-batman_792/index.html
Processing 19/75: Agnostic: A Spirited Manifesto
Failed to fetch https://books.toscrape.com/agnostic-a-spirited-manifesto_786/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/agnostic-a-spirited-manifesto_786/index.html
Processing 20/75: Walt Disney's Alice in Wonderland
Failed to fetch https://books.toscrape.com/walt-disneys-alice-in-wonderland_777/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/walt-disneys-alice-in-wonderland_777/index.html
Processing 21/75: Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)
Failed to fetch https://books.toscrape.com/superman-vol-1-before-truth-superman-by-gene-luen-yang-1_739/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/superman-vol-1-before-truth-superman-by-gene-luen-yang-1_739/index.html
Processing 22/75: Old School (Diary of a Wimpy Kid #10)
Failed to fetch https://books.toscrape.com/old-school-diary-of-a-wimpy-kid-10_723/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/old-school-diary-of-a-wimpy-kid-10_723/index.html
Processing 23/75: Lady Midnight (The Dark Artifices #1)
Failed to fetch https://books.toscrape.com/lady-midnight-the-dark-artifices-1_707/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/lady-midnight-the-dark-artifices-1_707/index.html
Processing 24/75: I Am Pilgrim (Pilgrim #1)
Failed to fetch https://books.toscrape.com/i-am-pilgrim-pilgrim-1_703/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/i-am-pilgrim-pilgrim-1_703/index.html
Processing 25/75: Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened
Failed to fetch https://books.toscrape.com/hyperbole-and-a-half-unfortunate-situations-flawed-coping-mechanisms-mayhem-and-other-things-that-happened_702/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/hyperbole-and-a-half-unfortunate-situations-flawed-coping-mechanisms-mayhem-and-other-things-that-happened_702/index.html
Processing 26/75: Greek Mythic History
Failed to fetch https://books.toscrape.com/greek-mythic-history_698/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/greek-mythic-history_698/index.html
Processing 27/75: Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years
Failed to fetch https://books.toscrape.com/far-away-places-on-the-brink-of-change-seven-continents-twenty-five-years_694/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/far-away-places-on-the-brink-of-change-seven-continents-twenty-five-years_694/index.html
Processing 28/75: Eight Hundred Grapes
Failed to fetch https://books.toscrape.com/eight-hundred-grapes_690/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/eight-hundred-grapes_690/index.html
Processing 29/75: Dear Mr. Knightley
Failed to fetch https://books.toscrape.com/dear-mr-knightley_684/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/dear-mr-knightley_684/index.html
Processing 30/75: City of Fallen Angels (The Mortal Instruments #4)
Failed to fetch https://books.toscrape.com/city-of-fallen-angels-the-mortal-instruments-4_677/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/city-of-fallen-angels-the-mortal-instruments-4_677/index.html
Processing 31/75: The Epidemic (The Program 0.6)
Failed to fetch https://books.toscrape.com/the-epidemic-the-program-06_636/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-epidemic-the-program-06_636/index.html
Processing 32/75: One with You (Crossfire #5)
Failed to fetch https://books.toscrape.com/one-with-you-crossfire-5_626/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/one-with-you-crossfire-5_626/index.html
Processing 33/75: The Sleep Revolution: Transforming Your Life, One Night at a Time
Failed to fetch https://books.toscrape.com/the-sleep-revolution-transforming-your-life-one-night-at-a-time_608/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-sleep-revolution-transforming-your-life-one-night-at-a-time_608/index.html
Processing 34/75: Mother, Can You Not?
Failed to fetch https://books.toscrape.com/mother-can-you-not_599/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/mother-can-you-not_599/index.html
Processing 35/75: A Gentleman's Position (Society of Gentlemen #3)
Failed to fetch https://books.toscrape.com/a-gentlemans-position-society-of-gentlemen-3_584/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-gentlemans-position-society-of-gentlemen-3_584/index.html
Processing 36/75: The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York
Failed to fetch https://books.toscrape.com/the-moosewood-cookbook-recipes-from-moosewood-restaurant-ithaca-new-york_574/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-moosewood-cookbook-recipes-from-moosewood-restaurant-ithaca-new-york_574/index.html
Processing 37/75: NaNo What Now? Finding your editing process, revising your NaNoWriMo book and building a writing career through publishing and beyond
Failed to fetch https://books.toscrape.com/nano-what-now-finding-your-editing-process-revising-your-nanowrimo-book-and-building-a-writing-career-through-publishing-and-beyond_566/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/nano-what-now-finding-your-editing-process-revising-your-nanowrimo-book-and-building-a-writing-career-through-publishing-and-beyond_566/index.html
Processing 38/75: Roller Girl
Failed to fetch https://books.toscrape.com/roller-girl_540/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/roller-girl_540/index.html
Processing 39/75: History of Beauty
Failed to fetch https://books.toscrape.com/history-of-beauty_521/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/history-of-beauty_521/index.html
Processing 40/75: The Origin of Species
Failed to fetch https://books.toscrape.com/the-origin-of-species_499/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-origin-of-species_499/index.html
Processing 41/75: Naturally Lean: 125 Nourishing Gluten-Free, Plant-Based Recipes--All Under 300 Calories
Failed to fetch https://books.toscrape.com/naturally-lean-125-nourishing-gluten-free-plant-based-recipes-all-under-300-calories_479/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/naturally-lean-125-nourishing-gluten-free-plant-based-recipes-all-under-300-calories_479/index.html
Processing 42/75: Life of Pi
Failed to fetch https://books.toscrape.com/life-of-pi_475/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/life-of-pi_475/index.html
Processing 43/75: Every Heart a Doorway (Every Heart A Doorway #1)
Failed to fetch https://books.toscrape.com/every-heart-a-doorway-every-heart-a-doorway-1_465/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/every-heart-a-doorway-every-heart-a-doorway-1_465/index.html
Processing 44/75: Counted With the Stars (Out from Egypt #1)
Failed to fetch https://books.toscrape.com/counted-with-the-stars-out-from-egypt-1_463/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/counted-with-the-stars-out-from-egypt-1_463/index.html
Processing 45/75: The Hobbit (Middle-Earth Universe)
Failed to fetch https://books.toscrape.com/the-hobbit-middle-earth-universe_447/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-hobbit-middle-earth-universe_447/index.html
Processing 46/75: The Collected Poems of W.B. Yeats (The Collected Works of W.B. Yeats #1)
Failed to fetch https://books.toscrape.com/the-collected-poems-of-wb-yeats-the-collected-works-of-wb-yeats-1_441/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-collected-poems-of-wb-yeats-the-collected-works-of-wb-yeats-1_441/index.html
Processing 47/75: Pride and Prejudice
Failed to fetch https://books.toscrape.com/pride-and-prejudice_437/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/pride-and-prejudice_437/index.html
Processing 48/75: The Secret Garden
Failed to fetch https://books.toscrape.com/the-secret-garden_413/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-secret-garden_413/index.html
Processing 49/75: The Power Greens Cookbook: 140 Delicious Superfood Recipes
Failed to fetch https://books.toscrape.com/the-power-greens-cookbook-140-delicious-superfood-recipes_410/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-power-greens-cookbook-140-delicious-superfood-recipes_410/index.html
Processing 50/75: The Darkest Corners
Failed to fetch https://books.toscrape.com/the-darkest-corners_399/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-darkest-corners_399/index.html
Processing 51/75: Shiver (The Wolves of Mercy Falls #1)
Failed to fetch https://books.toscrape.com/shiver-the-wolves-of-mercy-falls-1_392/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/shiver-the-wolves-of-mercy-falls-1_392/index.html
Processing 52/75: Kill the Boy Band
Failed to fetch https://books.toscrape.com/kill-the-boy-band_381/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/kill-the-boy-band_381/index.html
Processing 53/75: Booked
Failed to fetch https://books.toscrape.com/booked_365/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/booked_365/index.html
Processing 54/75: An Abundance of Katherines
Failed to fetch https://books.toscrape.com/an-abundance-of-katherines_362/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/an-abundance-of-katherines_362/index.html
Processing 55/75: A Feast for Crows (A Song of Ice and Fire #4)
Failed to fetch https://books.toscrape.com/a-feast-for-crows-a-song-of-ice-and-fire-4_357/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-feast-for-crows-a-song-of-ice-and-fire-4_357/index.html
Processing 56/75: The Gunning of America: Business and the Making of American Gun Culture
Failed to fetch https://books.toscrape.com/the-gunning-of-america-business-and-the-making-of-american-gun-culture_347/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-gunning-of-america-business-and-the-making-of-american-gun-culture_347/index.html
Processing 57/75: Some Women
Failed to fetch https://books.toscrape.com/some-women_341/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/some-women_341/index.html
Processing 58/75: Outlander (Outlander #1)
Failed to fetch https://books.toscrape.com/outlander-outlander-1_338/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/outlander-outlander-1_338/index.html
Processing 59/75: Night Shift (Night Shift #1-20)
Failed to fetch https://books.toscrape.com/night-shift-night-shift-1-20_335/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/night-shift-night-shift-1-20_335/index.html
Processing 60/75: The Elegant Universe: Superstrings, Hidden Dimensions, and the Quest for the Ultimate Theory
Failed to fetch https://books.toscrape.com/the-elegant-universe-superstrings-hidden-dimensions-and-the-quest-for-the-ultimate-theory_245/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-elegant-universe-superstrings-hidden-dimensions-and-the-quest-for-the-ultimate-theory_245/index.html
Processing 61/75: Scarlet (The Lunar Chronicles #2)
Failed to fetch https://books.toscrape.com/scarlet-the-lunar-chronicles-2_218/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/scarlet-the-lunar-chronicles-2_218/index.html
Processing 62/75: Running with Scissors
Failed to fetch https://books.toscrape.com/running-with-scissors_215/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/running-with-scissors_215/index.html
Processing 63/75: Ready Player One
Failed to fetch https://books.toscrape.com/ready-player-one_209/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/ready-player-one_209/index.html
Processing 64/75: Green Eggs and Ham (Beginner Books B-16)
Failed to fetch https://books.toscrape.com/green-eggs-and-ham-beginner-books-b-16_165/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/green-eggs-and-ham-beginner-books-b-16_165/index.html
Processing 65/75: Fifty Shades Freed (Fifty Shades #3)
Failed to fetch https://books.toscrape.com/fifty-shades-freed-fifty-shades-3_156/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/fifty-shades-freed-fifty-shades-3_156/index.html
Processing 66/75: Disrupted: My Misadventure in the Start-Up Bubble
Failed to fetch https://books.toscrape.com/disrupted-my-misadventure-in-the-start-up-bubble_148/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/disrupted-my-misadventure-in-the-start-up-bubble_148/index.html
Processing 67/75: A Visit from the Goon Squad
Failed to fetch https://books.toscrape.com/a-visit-from-the-goon-squad_117/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-visit-from-the-goon-squad_117/index.html
Processing 68/75: New Moon (Twilight #2)
Failed to fetch https://books.toscrape.com/new-moon-twilight-2_105/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/new-moon-twilight-2_105/index.html
Processing 69/75: Fruits Basket, Vol. 2 (Fruits Basket #2)
Failed to fetch https://books.toscrape.com/fruits-basket-vol-2-fruits-basket-2_100/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/fruits-basket-vol-2-fruits-basket-2_100/index.html
Processing 70/75: Y: The Last Man, Vol. 1: Unmanned (Y: The Last Man #1)
Failed to fetch https://books.toscrape.com/y-the-last-man-vol-1-unmanned-y-the-last-man-1_98/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/y-the-last-man-vol-1-unmanned-y-the-last-man-1_98/index.html
Processing 71/75: The Zombie Room
Failed to fetch https://books.toscrape.com/the-zombie-room_87/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-zombie-room_87/index.html
Processing 72/75: The Silent Wife
Failed to fetch https://books.toscrape.com/the-silent-wife_83/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-silent-wife_83/index.html
Processing 73/75: The Girl You Lost
Failed to fetch https://books.toscrape.com/the-girl-you-lost_66/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-girl-you-lost_66/index.html
Processing 74/75: The Edge of Reason (Bridget Jones #2)
Failed to fetch https://books.toscrape.com/the-edge-of-reason-bridget-jones-2_63/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/the-edge-of-reason-bridget-jones-2_63/index.html
Processing 75/75: A Spy's Devotion (The Regency Spies of London #1)
Failed to fetch https://books.toscrape.com/a-spys-devotion-the-regency-spies-of-london-1_3/index.html: 404 Client Error: Not Found for url: https://books.toscrape.com/a-spys-devotion-the-regency-spies-of-london-1_3/index.html
Saved detailed book data to books_detailed.csv
shape 75

,Title,Price (£),Rating,Availability,Link,UPC,Availability_Details,Number_of_Reviews,Description,Genre
0,Set Me Free,17.46,5,In stock,https://books.toscrape.com/catalogue/set-me-fr...,ce6396b0f23f6ecc,In stock (19 available),0,Aaron Ledbetterâs future had been planned ou...,Young Adult
1,The Four Agreements: A Practical Guide to Pers...,17.66,5,In stock,https://books.toscrape.com/the-four-agreements...,,,0,,
2,Sophie's World,15.94,5,In stock,https://books.toscrape.com/sophies-world_966/i...,,,0,,
3,Untitled Collection: Sabbath Poems 2014,14.27,4,In stock,https://books.toscrape.com/untitled-collection...,,,0,,
4,This One Summer,19.49,4,In stock,https://books.toscrape.com/this-one-summer_947...,,,0,,

In [23]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin
import re

BASE_URL = "https://books.toscrape.com/"

def rating_to_int(rating_class):
    """Convert rating text to integer"""
    ratings = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
    return ratings.get(rating_class, 0)

def extract_price(price_text):
    """Extract numeric price from text like '£51.77'"""
    match = re.search(r"£([0-9]+\.[0-9]+)", price_text)
    if match:
        return float(match.group(1))
    return 0.0

def scrape_books(limit=10, min_rating=4, max_price=20):
    books = []
    url = BASE_URL
    count = 0
    
    while url and count < limit:
        try:
            response = requests.get(url)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, "html.parser")
            
            for li in soup.select("ol.row li"):
                if count >= limit:
                    break
                
                title_elem = li.select_one("h3 a")
                price_elem = li.select_one(".product_price .price_color")
                availability_elem = li.select_one(".product_price .instock.availability")
                rating_elem = li.select_one("p.star-rating")
                
                if not all([title_elem, price_elem, availability_elem, rating_elem]):
                    continue
                
                title = title_elem["title"].strip()
                price = extract_price(price_elem.text.strip())
                availability = availability_elem.text.strip()
                rating_class = rating_elem.get("class", [])
                rating = rating_to_int(rating_class[1]) if len(rating_class) > 1 else 0
                
                # Filter by rating and price
                if rating < min_rating or price > max_price:
                    continue
                
                product_link = urljoin(BASE_URL, title_elem.get("href"))
                
                books.append({
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Availability": availability,
                    "Link": product_link
                })
                
                count += 1
                # Show progress
                print(f"Scraped {count}/{limit}: {title}")
            
            # Next page
            next_page = soup.select_one("li.next a")
            if next_page:
                next_url = next_page.get("href")
                url = urljoin(url, next_url)
            else:
                url = None
                
        except requests.RequestException as e:
            print(f"Request failed: {e}")
            break
    
    return pd.DataFrame(books)

# Example usage: scrape 10 books with rating >= 4 and price <= 20
if __name__ == "__main__":
    df = scrape_books(limit=100, min_rating=4, max_price=20)
    df.to_csv("books.csv", index=False)
    print("Saved data to books.csv")
print("shape", df.shape)
df.head(df.shape[0])

Scraped 1/100: Set Me Free
Scraped 2/100: The Four Agreements: A Practical Guide to Personal Freedom
Scraped 3/100: Sophie's World
Scraped 4/100: Untitled Collection: Sabbath Poems 2014
Scraped 5/100: This One Summer
Scraped 6/100: Thirst
Scraped 7/100: Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)
Scraped 8/100: Princess Between Worlds (Wide-Awake Princess #5)
Scraped 9/100: Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)
Scraped 10/100: Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed
Scraped 11/100: First and First (Five Boroughs #3)
Scraped 12/100: Camp Midnight
Scraped 13/100: The Third Wave: An Entrepreneurâs Vision of the Future
Scraped 14/100: The Stranger
Scraped 15/100: Something More Than This
Scraped 16/100: Poems That Make Grown Women Cry
Scraped 17/100: Dark Notes
Scraped 18/100: Batman: The Dark Knight Returns (Batman)
Scraped 19/100: Agnostic: A Spirited Manifesto
Scraped 20/100: Walt Disney's Alice in Wonderland
Scraped 21/100: Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)
Scraped 22/100: Old School (Diary of a Wimpy Kid #10)
Scraped 23/100: Lady Midnight (The Dark Artifices #1)
Scraped 24/100: I Am Pilgrim (Pilgrim #1)
Scraped 25/100: Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened
Scraped 26/100: Greek Mythic History
Scraped 27/100: Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years
Scraped 28/100: Eight Hundred Grapes
Scraped 29/100: Dear Mr. Knightley
Scraped 30/100: City of Fallen Angels (The Mortal Instruments #4)
Scraped 31/100: The Epidemic (The Program 0.6)
Scraped 32/100: One with You (Crossfire #5)
Scraped 33/100: The Sleep Revolution: Transforming Your Life, One Night at a Time
Scraped 34/100: Mother, Can You Not?
Scraped 35/100: A Gentleman's Position (Society of Gentlemen #3)
Scraped 36/100: The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York
Scraped 37/100: NaNo What Now? Finding your editing process, revising your NaNoWriMo book and building a writing career through publishing and beyond
Scraped 38/100: Roller Girl
Scraped 39/100: History of Beauty
Scraped 40/100: The Origin of Species
Scraped 41/100: Naturally Lean: 125 Nourishing Gluten-Free, Plant-Based Recipes--All Under 300 Calories
Scraped 42/100: Life of Pi
Scraped 43/100: Every Heart a Doorway (Every Heart A Doorway #1)
Scraped 44/100: Counted With the Stars (Out from Egypt #1)
Scraped 45/100: The Hobbit (Middle-Earth Universe)
Scraped 46/100: The Collected Poems of W.B. Yeats (The Collected Works of W.B. Yeats #1)
Scraped 47/100: Pride and Prejudice
Scraped 48/100: The Secret Garden
Scraped 49/100: The Power Greens Cookbook: 140 Delicious Superfood Recipes
Scraped 50/100: The Darkest Corners
Scraped 51/100: Shiver (The Wolves of Mercy Falls #1)
Scraped 52/100: Kill the Boy Band
Scraped 53/100: Booked
Scraped 54/100: An Abundance of Katherines
Scraped 55/100: A Feast for Crows (A Song of Ice and Fire #4)
Scraped 56/100: The Gunning of America: Business and the Making of American Gun Culture
Scraped 57/100: Some Women
Scraped 58/100: Outlander (Outlander #1)
Scraped 59/100: Night Shift (Night Shift #1-20)
Scraped 60/100: The Elegant Universe: Superstrings, Hidden Dimensions, and the Quest for the Ultimate Theory
Scraped 61/100: Scarlet (The Lunar Chronicles #2)
Scraped 62/100: Running with Scissors
Scraped 63/100: Ready Player One
Scraped 64/100: Green Eggs and Ham (Beginner Books B-16)
Scraped 65/100: Fifty Shades Freed (Fifty Shades #3)
Scraped 66/100: Disrupted: My Misadventure in the Start-Up Bubble
Scraped 67/100: A Visit from the Goon Squad
Scraped 68/100: New Moon (Twilight #2)
Scraped 69/100: Fruits Basket, Vol. 2 (Fruits Basket #2)
Scraped 70/100: Y: The Last Man, Vol. 1: Unmanned (Y: The Last Man #1)
Scraped 71/100: The Zombie Room
Scraped 72/100: The Silent Wife
Scraped 73/100: The Girl You Lost
Scraped 74/100: The Edge of Reason (Bridget Jones #2)
Scraped 75/100: A Spy's Devotion (The Regency Spies of London #1)
Saved data to books.csv
shape (75, 5)

,Title,Price (£),Rating,Availability,Link
0,Set Me Free,17.46,5,In stock,https://books.toscrape.com/catalogue/set-me-fr...
1,The Four Agreements: A Practical Guide to Pers...,17.66,5,In stock,https://books.toscrape.com/the-four-agreements...
2,Sophie's World,15.94,5,In stock,https://books.toscrape.com/sophies-world_966/i...
3,Untitled Collection: Sabbath Poems 2014,14.27,4,In stock,https://books.toscrape.com/untitled-collection...
4,This One Summer,19.49,4,In stock,https://books.toscrape.com/this-one-summer_947...
...,...,...,...,...,...
70,The Zombie Room,19.69,5,In stock,https://books.toscrape.com/the-zombie-room_87/...
71,The Silent Wife,12.34,5,In stock,https://books.toscrape.com/the-silent-wife_83/...
72,The Girl You Lost,12.29,5,In stock,https://books.toscrape.com/the-girl-you-lost_6...
73,The Edge of Reason (Bridget Jones #2),19.18,4,In stock,https://books.toscrape.com/the-edge-of-reason-...
74,A Spy's Devotion (The Regency Spies of London #1),16.97,5,In stock,https://books.toscrape.com/a-spys-devotion-the...

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin
import re

BASE_URL = "https://books.toscrape.com/"

def rating_to_int(rating_class):
    #Convert rating text to integer
    ratings = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
    return ratings.get(rating_class, 0)

def extract_price(price_text):
    #Extract numeric price from text like '£51.77
    match = re.search(r"£([0-9]+\.[0-9]+)", price_text)
    if match:
        return float(match.group(1))
    return 0.0

def scrape_books(limit=10, min_rating=4, max_price=20):
    books = []
    url = BASE_URL
    count = 0
    
    while url and count < limit:
        try:
            response = requests.get(url)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, "html.parser")
            
            for li in soup.select("ol.row li"):
                if count >= limit:
                    break
                
                title_elem = li.select_one("h3 a")
                price_elem = li.select_one(".product_price .price_color")
                availability_elem = li.select_one(".product_price .instock.availability")
                rating_elem = li.select_one("p.star-rating")
                
                if not all([title_elem, price_elem, availability_elem, rating_elem]):
                    continue
                
                title = title_elem["title"].strip()
                price = extract_price(price_elem.text.strip())
                availability = availability_elem.text.strip()
                rating_class = rating_elem.get("class", [])
                rating = rating_to_int(rating_class[1]) if len(rating_class) > 1 else 0
                
                # Filter by rating and price
                if rating < min_rating or price > max_price:
                    continue
                
                product_link = urljoin(BASE_URL, title_elem.get("href"))
                
                books.append({
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Availability": availability,
                    "Link": product_link
                })
                
                count += 1
            
            # Next page
            next_page = soup.select_one("li.next a")
            if next_page:
                next_url = next_page.get("href")
                url = urljoin(url, next_url)
            else:
                url = None
                
        except requests.RequestException as e:
            print(f"Request failed: {e}")
            break
    
    return pd.DataFrame(books)

# Example usage: scrape 10 books with rating >= 4 and price <= 20
if __name__ == "__main__":
    df = scrape_books(limit=10, min_rating=4, max_price=20)
    df.to_csv("test.csv", index=False)
    print("Saved data to test.csv")
    print("shape", df.shape)
df.head(10)

Saved filtered data to test.csv
shape (10, 5)

,Title,Price (£),Rating,Availability,Link
0,Set Me Free,17.46,5,In stock,https://books.toscrape.com/catalogue/set-me-fr...
1,The Four Agreements: A Practical Guide to Pers...,17.66,5,In stock,https://books.toscrape.com/the-four-agreements...
2,Sophie's World,15.94,5,In stock,https://books.toscrape.com/sophies-world_966/i...
3,Untitled Collection: Sabbath Poems 2014,14.27,4,In stock,https://books.toscrape.com/untitled-collection...
4,This One Summer,19.49,4,In stock,https://books.toscrape.com/this-one-summer_947...
5,Thirst,17.27,5,In stock,https://books.toscrape.com/thirst_946/index.html
6,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",13.61,5,In stock,https://books.toscrape.com/princess-jellyfish-...
7,Princess Between Worlds (Wide-Awake Princess #5),13.34,5,In stock,https://books.toscrape.com/princess-between-wo...
8,"Outcast, Vol. 1: A Darkness Surrounds Him (Out...",15.44,4,In stock,https://books.toscrape.com/outcast-vol-1-a-dar...
9,Mama Tried: Traditional Italian Cooking for th...,14.02,4,In stock,https://books.toscrape.com/mama-tried-traditio...

In [18]:
df.head()

,Title,Price (£),Rating,Availability,Link
0,Set Me Free,17.46,5,In stock,https://books.toscrape.com/catalogue/set-me-fr...
1,The Four Agreements: A Practical Guide to Pers...,17.66,5,In stock,https://books.toscrape.com/the-four-agreements...
2,Sophie's World,15.94,5,In stock,https://books.toscrape.com/sophies-world_966/i...
3,Untitled Collection: Sabbath Poems 2014,14.27,4,In stock,https://books.toscrape.com/untitled-collection...
4,This One Summer,19.49,4,In stock,https://books.toscrape.com/this-one-summer_947...

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin
import re

BASE_URL = "https://books.toscrape.com/"

def rating_to_int(rating_class):
    #Convert rating text to integer
    ratings = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
    return ratings.get(rating_class, 0)

def extract_price(price_text):
    #Extract numeric price from text like '£51.77
    match = re.search(r"£([0-9]+\.[0-9]+)", price_text)
    if match:
        return float(match.group(1))
    return 0.0

def scrape_books(limit=10):
    books = []
    url = BASE_URL
    count = 0
    
    while url and count < limit:
        try:
            response = requests.get(url)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, "html.parser")
            
            for li in soup.select("ol.row li"):
                if count >= limit:
                    break
                
                title_elem = li.select_one("h3 a")
                price_elem = li.select_one(".product_price .price_color")
                availability_elem = li.select_one(".product_price .instock.availability")
                rating_elem = li.select_one("p.star-rating")
                
                if not all([title_elem, price_elem, availability_elem, rating_elem]):
                    continue
                
                title = title_elem["title"].strip()
                price = extract_price(price_elem.text.strip())
                availability = availability_elem.text.strip()
                rating_class = rating_elem.get("class", [])
                rating = rating_to_int(rating_class[1]) if len(rating_class) > 1 else 0
                
                # Absolute URL of the product
                product_link = urljoin(BASE_URL, title_elem.get("href"))
                
                books.append({
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Availability": availability,
                    "Link": product_link
                })
                
                count += 1
            
            # Handle next page URL
            next_page = soup.select_one("li.next a")
            if next_page:
                next_url = next_page.get("href")
                url = urljoin(url, next_url)
            else:
                url = None
                
        except requests.RequestException as e:
            print(f"Request failed: {e}")
            break
    
    return pd.DataFrame(books)

# Example usage: scrape 10 books and save to CSV
if __name__ == "__main__":
    df = scrape_books(limit=10)
    df.to_csv("test.csv", index=False)
    print("Saved scraped data to test.csv")

Saved scraped data to test.csv

In [15]:
df.head()

,Title,Price (£),Rating,Availability,Link
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...

In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin
import re

BASE_URL = "https://books.toscrape.com/"

def rating_to_int(rating_class):
    """Convert rating text to integer"""
    ratings = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
    return ratings.get(rating_class, 0)

def extract_price(price_text):
    """Extract numeric price from text like '£51.77'"""
    match = re.search(r"£([0-9]+\.[0-9]+)", price_text)
    if match:
        return float(match.group(1))
    return 0.0

def scrape_books(limit=10):
    books = []
    url = BASE_URL
    count = 0
    
    while url and count < limit:
        try:
            response = requests.get(url)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, "html.parser")
            
            for li in soup.select("ol.row li"):
                if count >= limit:
                    break
                
                title_elem = li.select_one("h3 a")
                price_elem = li.select_one(".product_price .price_color")
                availability_elem = li.select_one(".product_price .instock.availability")
                rating_elem = li.select_one("p.star-rating")
                
                if not all([title_elem, price_elem, availability_elem, rating_elem]):
                    continue
                
                title = title_elem["title"].strip()
                price = extract_price(price_elem.text.strip())
                availability = availability_elem.text.strip()
                rating_class = rating_elem.get("class", [])
                rating = rating_to_int(rating_class[1]) if len(rating_class) > 1 else 0
                
                books.append({
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Availability": availability
                })
                
                count += 1
            
            # Handle next page URL
            next_page = soup.select_one("li.next a")
            if next_page:
                next_url = next_page.get("href")
                url = urljoin(url, next_url)
            else:
                url = None
                
        except requests.RequestException as e:
            print(f"Request failed: {e}")
            break
    
    return pd.DataFrame(books)

# Example usage: scrape 10 books and save to CSV
if __name__ == "__main__":
    df = scrape_books(limit=10)
    df.to_csv("test.csv", index=False)
    print("Saved scraped data to test.csv")

Saved scraped data to test.csv

In [13]:
df.head()

                                   Title  Price (£)  Rating Availability
0                   A Light in the Attic      51.77       3     In stock
1                     Tipping the Velvet      53.74       1     In stock
2                             Soumission      50.10       1     In stock
3                          Sharp Objects      47.82       4     In stock
4  Sapiens: A Brief History of Humankind      54.23       5     In stock

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

# Map textual ratings to numeric values
RATING_MAP = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

def scrape_books(min_rating=4, max_price=20):
    """
    Scrape books from 'Books to Scrape' with a minimum rating and maximum price.
    
    Parameters:
    min_rating (int): Minimum rating of the book (1-5)
    max_price (float): Maximum price in £

    Returns:
    pandas.DataFrame: DataFrame containing UPC, Title, Price, Rating, Genre, Availability, Description
    """
    
    base_url = "http://books.toscrape.com/catalogue/page-{}.html"
    all_books = []
    page = 1
    
    while True:
        url = base_url.format(page)
        response = requests.get(url)
        if response.status_code != 200:
            break
        
        soup = BeautifulSoup(response.text, "html.parser")
        books = soup.find_all("article", class_="product_pod")
        if not books:
            break
        
        for book in books:
            # Book title
            title = book.h3.a["title"]
            
            # Price (robust cleaning to handle weird characters)
            price_text = book.find("p", class_="price_color").text
            price_clean = re.sub(r"[^0-9.]", "", price_text)  # Keep digits and dot
            price = float(price_clean)
            
            # Rating
            rating_class = book.p["class"][1]
            rating = RATING_MAP.get(rating_class, 0)
            
            # Availability
            availability = book.find("p", class_="instock availability").text.strip()
            
            # Visit book detail page for UPC, Description, and Genre
            book_url = "http://books.toscrape.com/catalogue/" + book.h3.a["href"].replace("../", "")
            book_resp = requests.get(book_url)
            book_soup = BeautifulSoup(book_resp.text, "html.parser")
            
            # UPC
            upc_tag = book_soup.find("th", text="UPC")
            upc = upc_tag.find_next_sibling("td").text if upc_tag else "Unknown"
            
            # Description
            desc_tag = book_soup.find("meta", attrs={"name": "description"})
            description = desc_tag["content"].strip() if desc_tag else ""
            
            # Genre from breadcrumb
            breadcrumb_items = book_soup.find("ul", class_="breadcrumb").find_all("li")
            genre = breadcrumb_items[2].text.strip() if len(breadcrumb_items) >= 3 else "Unknown"
            
            # Filter by rating and price
            if rating >= min_rating and price <= max_price:
                all_books.append({
                    "UPC": upc,
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Genre": genre,
                    "Availability": availability,
                    "Description": description
                })
        
        page += 1
    
    return pd.DataFrame(all_books)

# Example usage: scrape books with rating >=4 and price <= £20
df = scrape_books(min_rating=4, max_price=20)
print(df.head())

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

# Map textual ratings to numeric values
RATING_MAP = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

def scrape_books(min_rating=4, max_price=20):
    """
    Scrape books from 'Books to Scrape' with a minimum rating and maximum price.
    
    Parameters:
    min_rating (int): Minimum rating of the book (1-5)
    max_price (float): Maximum price in £

    Returns:
    pandas.DataFrame: DataFrame containing UPC, Title, Price, Rating, Genre, Availability, Description
    """
    
    base_url = "http://books.toscrape.com/catalogue/page-{}.html"
    all_books = []
    page = 1
    
    while True:
        url = base_url.format(page)
        response = requests.get(url)
        if response.status_code != 200:
            break
        
        soup = BeautifulSoup(response.text, "html.parser")
        books = soup.find_all("article", class_="product_pod")
        if not books:
            break
        
        for book in books:
            # Book title
            title = book.h3.a["title"]
            
            # Price (robust cleaning to handle weird characters)
            price_text = book.find("p", class_="price_color").text
            price_clean = re.sub(r"[^0-9.]", "", price_text)  # Keep digits and dot
            price = float(price_clean)
            
            # Rating
            rating_class = book.p["class"][1]
            rating = RATING_MAP.get(rating_class, 0)
            
            # Availability
            availability = book.find("p", class_="instock availability").text.strip()
            
            # Visit book detail page for UPC, Description, and Genre
            book_url = "http://books.toscrape.com/catalogue/" + book.h3.a["href"].replace("../", "")
            book_resp = requests.get(book_url)
            book_soup = BeautifulSoup(book_resp.text, "html.parser")
            
            # UPC (fixed to avoid deprecation warning)
            upc_tag = book_soup.find("th", string="UPC")
            upc = upc_tag.find_next_sibling("td").text if upc_tag else "Unknown"
            
            # Description
            desc_tag = book_soup.find("meta", attrs={"name": "description"})
            description = desc_tag["content"].strip() if desc_tag else ""
            
            # Genre from breadcrumb
            breadcrumb_items = book_soup.find("ul", class_="breadcrumb").find_all("li")
            genre = breadcrumb_items[2].text.strip() if len(breadcrumb_items) >= 3 else "Unknown"
            
            # Filter by rating and price
            if rating >= min_rating and price <= max_price:
                all_books.append({
                    "UPC": upc,
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Genre": genre,
                    "Availability": availability,
                    "Description": description
                })
        
        page += 1
    
    return pd.DataFrame(all_books)

# Example usage: scrape books with rating >= 4 and price <= £20
df = scrape_books(min_rating=4, max_price=20)
print(df.head())